openapi: 3.0.1
info:
  title: Bronze Assistant API
  description: BronzeApp Assistant για καμπίνες, καθρέφτες, accessories
  version: "1.0"
servers:
  - url: https://bronze-assistant-alt.vercel.app
paths:
  /api/assistant:
    post:
      summary: Κάνε ερώτηση στον βοηθό
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                  example: Τι καμπίνα να επιλέξω για 120x190;
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
