// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqliteLabelingDatabase;

#nullable disable

namespace SqliteLabelingDatabase.Migrations
{
    [DbContext(typeof(AccessoriesLabelsDbContext))]
    partial class AccessoriesLabelsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SqliteLabelingDatabase.AccessoryLabelDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionEnglish")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionGreek")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishEnglish")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishGreek")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("MountingTypeEnglish")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MountingTypeGreek")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Photo")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("PrimaryTypeEnglish")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryTypeGreek")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryTypeEnglish")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryTypeGreek")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesEnglish")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesGreek")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AccessoriesTable");
                });
#pragma warning restore 612, 618
        }
    }
}
