using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CommonInterfacesBronze
{
    /// <summary>
    /// An Object which has a Code property that can also be AutoGenerated
    /// </summary>
    public interface IAutoGeneratedCodeable : ICodeable
    {
        /// <summary>
        /// Returns the AutoGenerated Code for the Current state of the Object
        /// This does not mean that the Code Property will also return this (Depends on the implementation AutoGeneration might be overriden)
        /// </summary>
        /// <returns></returns>
        public string GetGeneratedCode();
    }
}
