// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqliteApplicationSettings;

#nullable disable

namespace SqliteApplicationSettings.Migrations
{
    [DbContext(typeof(SettingsDbContext))]
    partial class SettingsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SqliteApplicationSettings.DTOs.GeneralApplicationSettingDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoStringObject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GeneralSettingsTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InfoStringObject = "",
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SettingName = "SelectedTheme",
                            SettingValue = "Dark"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InfoStringObject = "",
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SettingName = "SelectedLanguage",
                            SettingValue = "el-GR"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InfoStringObject = "",
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SettingName = "ApplicationVersion",
                            SettingValue = "Ver2.17-17-12-2023"
                        });
                });

            modelBuilder.Entity("SqliteApplicationSettings.DTOs.GlassesStockServiceSettingsDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AllowedHeightDifference")
                        .HasColumnType("REAL");

                    b.Property<double>("AllowedLengthDifference")
                        .HasColumnType("REAL");

                    b.Property<int>("ConcernsModel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoStringObject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShouldCompareFinish")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShouldCompareHeight")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShouldCompareLength")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShouldCompareThickness")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConcernsModel", "IsDefault")
                        .IsUnique();

                    b.ToTable("GlassesStockServiceUserSettingsTable", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 0,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 179, DateTimeKind.Local).AddTicks(6112),
                            InfoStringObject = "DefaultSettings-Model9A",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 2,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 0,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6547),
                            InfoStringObject = "UserSettings-Model9A",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 3,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 1,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6694),
                            InfoStringObject = "DefaultSettings-Model9S",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 4,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 1,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6702),
                            InfoStringObject = "UserSettings-Model9S",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 5,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 2,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6707),
                            InfoStringObject = "DefaultSettings-Model94",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 6,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 2,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6711),
                            InfoStringObject = "UserSettings-Model94",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 7,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 3,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6718),
                            InfoStringObject = "DefaultSettings-Model9F",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 8,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 3,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6723),
                            InfoStringObject = "UserSettings-Model9F",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 9,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 4,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6727),
                            InfoStringObject = "DefaultSettings-Model9B",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 10,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 4,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6730),
                            InfoStringObject = "UserSettings-Model9B",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 11,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 5,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6735),
                            InfoStringObject = "DefaultSettings-ModelW",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 12,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 5,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6739),
                            InfoStringObject = "UserSettings-ModelW",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 13,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 6,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6743),
                            InfoStringObject = "DefaultSettings-ModelHB",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 14,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 6,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6746),
                            InfoStringObject = "UserSettings-ModelHB",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 15,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 7,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6750),
                            InfoStringObject = "DefaultSettings-ModelNP",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 16,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 7,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6754),
                            InfoStringObject = "UserSettings-ModelNP",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 17,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 8,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6758),
                            InfoStringObject = "DefaultSettings-ModelVS",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 18,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 8,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6761),
                            InfoStringObject = "UserSettings-ModelVS",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 19,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 9,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6766),
                            InfoStringObject = "DefaultSettings-ModelVF",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 20,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 9,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6770),
                            InfoStringObject = "UserSettings-ModelVF",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 21,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 10,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6774),
                            InfoStringObject = "DefaultSettings-ModelV4",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 22,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 10,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6777),
                            InfoStringObject = "UserSettings-ModelV4",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 23,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 11,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6781),
                            InfoStringObject = "DefaultSettings-ModelVA",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 24,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 11,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6784),
                            InfoStringObject = "UserSettings-ModelVA",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 25,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 12,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6788),
                            InfoStringObject = "DefaultSettings-ModelWS",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 26,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 12,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6791),
                            InfoStringObject = "UserSettings-ModelWS",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 27,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 13,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6795),
                            InfoStringObject = "DefaultSettings-ModelE",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 28,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 13,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6798),
                            InfoStringObject = "UserSettings-ModelE",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 29,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 14,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6802),
                            InfoStringObject = "DefaultSettings-ModelWFlipper",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 30,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 14,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6806),
                            InfoStringObject = "UserSettings-ModelWFlipper",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 31,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 15,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6809),
                            InfoStringObject = "DefaultSettings-ModelDB",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 32,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 15,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6813),
                            InfoStringObject = "UserSettings-ModelDB",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 33,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 16,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6817),
                            InfoStringObject = "DefaultSettings-ModelNB",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 34,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 16,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6820),
                            InfoStringObject = "UserSettings-ModelNB",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 35,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 17,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6825),
                            InfoStringObject = "DefaultSettings-ModelNV",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 36,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 17,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6829),
                            InfoStringObject = "UserSettings-ModelNV",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 37,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 18,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6832),
                            InfoStringObject = "DefaultSettings-ModelMV2",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 38,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 18,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6836),
                            InfoStringObject = "UserSettings-ModelMV2",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 39,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 19,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6839),
                            InfoStringObject = "DefaultSettings-ModelNV2",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 40,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 19,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6843),
                            InfoStringObject = "UserSettings-ModelNV2",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 41,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 20,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6846),
                            InfoStringObject = "DefaultSettings-Model6WA",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 42,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 20,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6850),
                            InfoStringObject = "UserSettings-Model6WA",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 43,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 21,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6854),
                            InfoStringObject = "DefaultSettings-Model9C",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 44,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 21,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6857),
                            InfoStringObject = "UserSettings-Model9C",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 45,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 22,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6861),
                            InfoStringObject = "DefaultSettings-Model8W40",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 46,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 22,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6864),
                            InfoStringObject = "UserSettings-Model8W40",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 47,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 23,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6868),
                            InfoStringObject = "DefaultSettings-ModelGlassContainer",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 48,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 23,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6872),
                            InfoStringObject = "UserSettings-ModelGlassContainer",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 49,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 24,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6876),
                            InfoStringObject = "DefaultSettings-ModelQB",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 50,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 24,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6885),
                            InfoStringObject = "UserSettings-ModelQB",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 51,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 25,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6889),
                            InfoStringObject = "DefaultSettings-ModelQP",
                            IsDefault = true,
                            IsSelected = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        },
                        new
                        {
                            Id = 52,
                            AllowedHeightDifference = 50.0,
                            AllowedLengthDifference = 50.0,
                            ConcernsModel = 25,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 181, DateTimeKind.Local).AddTicks(6892),
                            InfoStringObject = "UserSettings-ModelQP",
                            IsDefault = false,
                            IsSelected = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShouldCompareFinish = true,
                            ShouldCompareHeight = true,
                            ShouldCompareLength = true,
                            ShouldCompareThickness = false
                        });
                });

            modelBuilder.Entity("SqliteApplicationSettings.DTOs.SearchOrdersViewSettingsDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoStringObject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxResultsGetSmallOrders")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SearchOrdersViewSettingsTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 174, DateTimeKind.Local).AddTicks(8868),
                            InfoStringObject = "DefaultSettings",
                            IsDefault = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxResultsGetSmallOrders = 10
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2024, 11, 17, 2, 3, 3, 177, DateTimeKind.Local).AddTicks(4683),
                            InfoStringObject = "UserSettings",
                            IsDefault = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxResultsGetSmallOrders = 10
                        });
                });

            modelBuilder.Entity("SqliteApplicationSettings.DTOs.XlsSettingsGlassesDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("FirstColumnIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstRowIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FontColorA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FontColorB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FontColorG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FontColorR")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("FontSize")
                        .HasColumnType("REAL");

                    b.Property<int>("GeneralHeaderBackgroundColorA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GeneralHeaderBackgroundColorB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GeneralHeaderBackgroundColorG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GeneralHeaderBackgroundColorR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GeneralHeaderFontColorA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GeneralHeaderFontColorB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GeneralHeaderFontColorG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GeneralHeaderFontColorR")
                        .HasColumnType("INTEGER");

                    b.Property<double>("GeneralHeaderFontSize")
                        .HasColumnType("REAL");

                    b.Property<string>("GeneralHeaderHorizontalAlignment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("GeneralHeaderIsFontBold")
                        .HasColumnType("INTEGER");

                    b.Property<double>("GeneralHeaderRowHeight")
                        .HasColumnType("REAL");

                    b.Property<string>("GeneralHeaderVerticalAlignment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GlassTableAlternatingRowTableBackgroundColorA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlassTableAlternatingRowTableBackgroundColorB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlassTableAlternatingRowTableBackgroundColorG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlassTableAlternatingRowTableBackgroundColorR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlassTableHorizontalBorderColorA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlassTableHorizontalBorderColorB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlassTableHorizontalBorderColorG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlassTableHorizontalBorderColorR")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GlassTableHorizontalBorderThickness")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GlassTablePerimetricalBorderColorA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlassTablePerimetricalBorderColorB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlassTablePerimetricalBorderColorG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlassTablePerimetricalBorderColorR")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GlassTablePerimetricalBorderThickness")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GlassTableVerticalBorderColorA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlassTableVerticalBorderColorB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlassTableVerticalBorderColorG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlassTableVerticalBorderColorR")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GlassTableVerticalBorderThickness")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HorizontalAlignment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoStringObject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFontBold")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTitlesFontBold")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<double>("NormalRowHeight")
                        .HasColumnType("REAL");

                    b.Property<int>("NotesBackgroundColorA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotesBackgroundColorB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotesBackgroundColorG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotesBackgroundColorR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotesFontColorA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotesFontColorB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotesFontColorG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotesFontColorR")
                        .HasColumnType("INTEGER");

                    b.Property<double>("NotesFontSize")
                        .HasColumnType("REAL");

                    b.Property<string>("NotesHorizontalAlignment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotesIsFontBold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotesVerticalAlignment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfRowsForNotes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingsName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TableHeaderBackgroundColorA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TableHeaderBackgroundColorB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TableHeaderBackgroundColorG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TableHeaderBackgroundColorR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TableHeaderFontColorA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TableHeaderFontColorB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TableHeaderFontColorG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TableHeaderFontColorR")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TableHeaderFontSize")
                        .HasColumnType("REAL");

                    b.Property<string>("TableHeaderHorizontalAlignment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TableHeaderIsFontBold")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TableHeaderRowHeight")
                        .HasColumnType("REAL");

                    b.Property<string>("TableHeaderVerticalAlignment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TitlesBackgroundColorA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TitlesBackgroundColorB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TitlesBackgroundColorG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TitlesBackgroundColorR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TitlesFontColorA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TitlesFontColorB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TitlesFontColorG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TitlesFontColorR")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TitlesRowHeight")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalGlassesBoxBackgroundColorA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalGlassesBoxBackgroundColorB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalGlassesBoxBackgroundColorG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalGlassesBoxBackgroundColorR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalGlassesBoxFontColorA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalGlassesBoxFontColorB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalGlassesBoxFontColorG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalGlassesBoxFontColorR")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalGlassesBoxFontSize")
                        .HasColumnType("REAL");

                    b.Property<string>("TotalGlassesBoxHorizontalAlignment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TotalGlassesBoxIsFontBold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TotalGlassesBoxVerticalAlignment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalRows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VerticalAlignment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorksheetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsSelected");

                    b.HasIndex("SettingsName")
                        .IsUnique();

                    b.ToTable("XlsSettingsGlassesTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstColumnIndex = 1,
                            FirstRowIndex = 1,
                            FontColorA = 255,
                            FontColorB = 106,
                            FontColorG = 84,
                            FontColorR = 68,
                            FontFamily = "Calibri",
                            FontSize = 11.0,
                            GeneralHeaderBackgroundColorA = 0,
                            GeneralHeaderBackgroundColorB = 230,
                            GeneralHeaderBackgroundColorG = 230,
                            GeneralHeaderBackgroundColorR = 231,
                            GeneralHeaderFontColorA = 255,
                            GeneralHeaderFontColorB = 0,
                            GeneralHeaderFontColorG = 0,
                            GeneralHeaderFontColorR = 0,
                            GeneralHeaderFontSize = 22.0,
                            GeneralHeaderHorizontalAlignment = "Center",
                            GeneralHeaderIsFontBold = true,
                            GeneralHeaderRowHeight = 39.75,
                            GeneralHeaderVerticalAlignment = "Center",
                            GlassTableAlternatingRowTableBackgroundColorA = 255,
                            GlassTableAlternatingRowTableBackgroundColorB = 242,
                            GlassTableAlternatingRowTableBackgroundColorG = 242,
                            GlassTableAlternatingRowTableBackgroundColorR = 242,
                            GlassTableHorizontalBorderColorA = 255,
                            GlassTableHorizontalBorderColorB = 219,
                            GlassTableHorizontalBorderColorG = 169,
                            GlassTableHorizontalBorderColorR = 142,
                            GlassTableHorizontalBorderThickness = "Medium",
                            GlassTablePerimetricalBorderColorA = 255,
                            GlassTablePerimetricalBorderColorB = 0,
                            GlassTablePerimetricalBorderColorG = 0,
                            GlassTablePerimetricalBorderColorR = 0,
                            GlassTablePerimetricalBorderThickness = "Medium",
                            GlassTableVerticalBorderColorA = 255,
                            GlassTableVerticalBorderColorB = 219,
                            GlassTableVerticalBorderColorG = 169,
                            GlassTableVerticalBorderColorR = 142,
                            GlassTableVerticalBorderThickness = "None",
                            HorizontalAlignment = "Center",
                            InfoStringObject = "",
                            IsFontBold = true,
                            IsSelected = true,
                            IsTitlesFontBold = true,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NormalRowHeight = 19.5,
                            NotesBackgroundColorA = 255,
                            NotesBackgroundColorB = 242,
                            NotesBackgroundColorG = 242,
                            NotesBackgroundColorR = 242,
                            NotesFontColorA = 255,
                            NotesFontColorB = 0,
                            NotesFontColorG = 0,
                            NotesFontColorR = 0,
                            NotesFontSize = 12.0,
                            NotesHorizontalAlignment = "Center",
                            NotesIsFontBold = true,
                            NotesVerticalAlignment = "Center",
                            NumberOfRowsForNotes = 5,
                            SettingsName = "DefaultSettings",
                            TableHeaderBackgroundColorA = 255,
                            TableHeaderBackgroundColorB = 230,
                            TableHeaderBackgroundColorG = 230,
                            TableHeaderBackgroundColorR = 231,
                            TableHeaderFontColorA = 255,
                            TableHeaderFontColorB = 0,
                            TableHeaderFontColorG = 0,
                            TableHeaderFontColorR = 0,
                            TableHeaderFontSize = 16.0,
                            TableHeaderHorizontalAlignment = "Left",
                            TableHeaderIsFontBold = false,
                            TableHeaderRowHeight = 39.75,
                            TableHeaderVerticalAlignment = "Center",
                            TitlesBackgroundColorA = 255,
                            TitlesBackgroundColorB = 196,
                            TitlesBackgroundColorG = 114,
                            TitlesBackgroundColorR = 68,
                            TitlesFontColorA = 255,
                            TitlesFontColorB = 255,
                            TitlesFontColorG = 255,
                            TitlesFontColorR = 255,
                            TitlesRowHeight = 20.0,
                            TotalGlassesBoxBackgroundColorA = 255,
                            TotalGlassesBoxBackgroundColorB = 242,
                            TotalGlassesBoxBackgroundColorG = 242,
                            TotalGlassesBoxBackgroundColorR = 242,
                            TotalGlassesBoxFontColorA = 255,
                            TotalGlassesBoxFontColorB = 0,
                            TotalGlassesBoxFontColorG = 0,
                            TotalGlassesBoxFontColorR = 0,
                            TotalGlassesBoxFontSize = 16.0,
                            TotalGlassesBoxHorizontalAlignment = "Center",
                            TotalGlassesBoxIsFontBold = true,
                            TotalGlassesBoxVerticalAlignment = "Center",
                            TotalRows = 2000,
                            VerticalAlignment = "Center",
                            WorksheetName = "GlassesOrderSheet"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
