global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using MongoDB;
global using MongoDB.Bson.Serialization.Attributes;
global using MongoDbCommonLibrary.CommonEntities;
global using MongoDbCommonLibrary.CommonExceptions;
global using ShowerEnclosuresModelsLibrary.Models.RepositoryModels.ModelsSettings;
global using ShowerEnclosuresModelsLibrary.Models.CabinAllParts.PartsModels;
global using ShowerEnclosuresModelsLibrary.Models.CabinAllParts.PartsModels.AngleModels;
global using ShowerEnclosuresModelsLibrary.Models.CabinAllParts.PartsModels.HandlesModels;
global using ShowerEnclosuresModelsLibrary.Models.CabinAllParts.PartsModels.HingesModels;
global using ShowerEnclosuresModelsLibrary.Models.CabinAllParts.PartsModels.ProfilesModels;
global using ShowerEnclosuresModelsLibrary.Models.CabinAllParts.PartsModels.StripsModels;
global using ShowerEnclosuresModelsLibrary.Models.CabinAllParts.PartsModels.SupportsModels;
global using ShowerEnclosuresModelsLibrary.Models.SeriesModels.B6000Models.ConstraintsModels;
global using ShowerEnclosuresModelsLibrary.Models.SeriesModels.B6000Models.PartsModels;
global using ShowerEnclosuresModelsLibrary.Models.SeriesModels.DBModels;
global using ShowerEnclosuresModelsLibrary.Models.SeriesModels.FreeModels.ConstraintsModels;
global using ShowerEnclosuresModelsLibrary.Models.SeriesModels.FreeModels.PartsModels;
global using ShowerEnclosuresModelsLibrary.Models.SeriesModels.HBModels;
global using ShowerEnclosuresModelsLibrary.Models.SeriesModels.Inox304Models.ConstraintsModels;
global using ShowerEnclosuresModelsLibrary.Models.SeriesModels.Inox304Models.PartsModels;
global using ShowerEnclosuresModelsLibrary.Models.SeriesModels.NBModels;
global using ShowerEnclosuresModelsLibrary.Models.SeriesModels.NPModels;
global using ShowerEnclosuresModelsLibrary.Models.SeriesModels.WSSmartModels;



