using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BronzeFactoryApplication.ApplicationServices;


public class ImagesMappings
{
    public static readonly string ImagesFolderUri = @"/BronzeFactoryApplication;component/Resources/Images/";
    public static readonly string SketchesRelativeFolder = @"CabinsImages/CabinsDrawSketches/";
    public static readonly string SketchesSidesRelativeFolder = @"CabinsImages/SidesDrawSketches/";

    /// <summary>
    /// Appends the Folder URI to get the FullPath of the Image
    /// </summary>
    /// <param name="imageName">The Name of the Image</param>
    /// /// <param name="fileExtension">The file Extension</param>
    /// <returns></returns>
    public static string GetImagePath(string relativeFolderURI, string imageName, string fileExtension = ".png")
    {
        StringBuilder builder = new(ImagesFolderUri);
        return builder.Append(relativeFolderURI).Append(imageName).Append(fileExtension).ToString();
    }
    public static string GetSketchDrawImage(string imageName, string fileExtension = ".png")
    {
        return GetImagePath(SketchesRelativeFolder, imageName, fileExtension);
    }
    public static string GetSideSketchDrawImage(string imageName,string fileExtension = ".png")
    {
        return GetImagePath(SketchesSidesRelativeFolder, imageName, fileExtension);
    }

    /// <summary>
    /// A Dictionary Containing all the Image Resources
    /// </summary>
    public Dictionary<CabinDrawNumber, string> CabinDrawImage = new()
    {
        {CabinDrawNumber.None ,                        GetImagePath(string.Empty,"NoImageAvailable",".jpg")},
        {CabinDrawNumber.Draw9S ,                      GetSketchDrawImage("S")},
        {CabinDrawNumber.Draw9S9F ,                    GetSketchDrawImage("SF")},
        {CabinDrawNumber.Draw9S9F9F ,                  GetSketchDrawImage("SFF")},
        {CabinDrawNumber.Draw94 ,                      GetSketchDrawImage("4")},
        {CabinDrawNumber.Draw949F ,                    GetSketchDrawImage("4F")},
        {CabinDrawNumber.Draw949F9F ,                  GetSketchDrawImage("4FF")},
        {CabinDrawNumber.Draw9A ,                      GetSketchDrawImage("A")},
        {CabinDrawNumber.Draw9A9F ,                    GetSketchDrawImage("AF")},
        {CabinDrawNumber.Draw9C ,                      GetSketchDrawImage("C")},
        {CabinDrawNumber.Draw9C9F ,                    GetSketchDrawImage("CF")},
        {CabinDrawNumber.Draw9B ,                      GetSketchDrawImage("B")},
        {CabinDrawNumber.Draw9B9F ,                    GetSketchDrawImage("BF")},
        {CabinDrawNumber.Draw9B9F9F ,                  GetSketchDrawImage("BFF")},
        {CabinDrawNumber.DrawVS ,                      GetSketchDrawImage("S")},
        {CabinDrawNumber.DrawVSVF ,                    GetSketchDrawImage("SF")},
        {CabinDrawNumber.DrawV4 ,                      GetSketchDrawImage("4")},
        {CabinDrawNumber.DrawV4VF ,                    GetSketchDrawImage("4F")},
        {CabinDrawNumber.DrawVA ,                      GetSketchDrawImage("A")},
        {CabinDrawNumber.DrawWS ,                      GetSketchDrawImage("WS")},
        {CabinDrawNumber.DrawNP44 ,                    GetSketchDrawImage("44")},
        {CabinDrawNumber.Draw2CornerNP46 ,             GetSketchDrawImage("46")},
        {CabinDrawNumber.Draw2StraightNP48 ,           GetSketchDrawImage("48")},
        {CabinDrawNumber.DrawCornerNP6W45 ,            GetSketchDrawImage("45")},
        {CabinDrawNumber.DrawStraightNP6W47 ,          GetSketchDrawImage("47")},
        {CabinDrawNumber.DrawNB31 ,                    GetSketchDrawImage("31")},
        {CabinDrawNumber.DrawCornerNB6W32 ,            GetSketchDrawImage("32")},
        {CabinDrawNumber.Draw2CornerNB33 ,             GetSketchDrawImage("33")},
        {CabinDrawNumber.DrawStraightNB6W38 ,          GetSketchDrawImage("38")},
        {CabinDrawNumber.Draw2StraightNB41 ,           GetSketchDrawImage("41")},
        {CabinDrawNumber.DrawDB51 ,                    GetSketchDrawImage("51")},
        {CabinDrawNumber.DrawCornerDB8W52 ,            GetSketchDrawImage("52")},
        {CabinDrawNumber.Draw2CornerDB53 ,             GetSketchDrawImage("53")},
        {CabinDrawNumber.DrawStraightDB8W59 ,          GetSketchDrawImage("59")},
        {CabinDrawNumber.Draw2StraightDB61 ,           GetSketchDrawImage("61")},
        {CabinDrawNumber.DrawHB34 ,                    GetSketchDrawImage("34")},
        {CabinDrawNumber.DrawCornerHB8W35 ,            GetSketchDrawImage("35")},
        {CabinDrawNumber.Draw2CornerHB37 ,             GetSketchDrawImage("37")},
        {CabinDrawNumber.DrawStraightHB8W40 ,          GetSketchDrawImage("40")},
        {CabinDrawNumber.Draw2StraightHB43 ,           GetSketchDrawImage("43")},
        {CabinDrawNumber.Draw8W ,                      GetSketchDrawImage("W")},
        {CabinDrawNumber.DrawE ,                       GetSketchDrawImage("E")},
        {CabinDrawNumber.Draw8WFlipper81 ,             GetSketchDrawImage("81")},
        {CabinDrawNumber.Draw2Corner8W82 ,             GetSketchDrawImage("82")},
        {CabinDrawNumber.Draw1Corner8W84 ,             GetSketchDrawImage("84")},
        {CabinDrawNumber.Draw2Straight8W85 ,           GetSketchDrawImage("85")},
        {CabinDrawNumber.Draw2CornerStraight8W88 ,     GetSketchDrawImage("88")},
        {CabinDrawNumber.DrawMV2 ,                     GetSketchDrawImage("MV2")},
        {CabinDrawNumber.DrawNV2 ,                     GetSketchDrawImage("NV2")},
        {CabinDrawNumber.DrawNV ,                      GetSketchDrawImage("NV")},
        {CabinDrawNumber.Draw9F ,                      GetSketchDrawImage("F")},
        {CabinDrawNumber.DrawVF ,                      GetSketchDrawImage("F")},
        {CabinDrawNumber.DrawQP44 ,                    GetSketchDrawImage("44")},
        {CabinDrawNumber.Draw2CornerQP46 ,             GetSketchDrawImage("46")},
        {CabinDrawNumber.Draw2StraightQP48 ,           GetSketchDrawImage("48")},
        {CabinDrawNumber.DrawCornerQP6W45 ,            GetSketchDrawImage("45")},
        {CabinDrawNumber.DrawStraightQP6W47 ,          GetSketchDrawImage("47")},
        {CabinDrawNumber.DrawQB31 ,                    GetSketchDrawImage("31")},
        {CabinDrawNumber.DrawCornerQB6W32 ,            GetSketchDrawImage("32")},
        {CabinDrawNumber.Draw2CornerQB33 ,             GetSketchDrawImage("33")},
        {CabinDrawNumber.DrawStraightQB6W38 ,          GetSketchDrawImage("38")},
        {CabinDrawNumber.Draw2StraightQB41 ,           GetSketchDrawImage("41")},
    };
    public Dictionary<(CabinDrawNumber, CabinSynthesisModel), string> CabinDrawSideImage = new()
    {
            { (CabinDrawNumber.None,                    CabinSynthesisModel.Primary), GetImagePath(string.Empty,"Icons/QuestionMark",".png")},
            { (CabinDrawNumber.Draw9S,                  CabinSynthesisModel.Primary), GetSideSketchDrawImage("SPrimary" )},
            { (CabinDrawNumber.Draw9S9F,                CabinSynthesisModel.Primary), GetSideSketchDrawImage("SFPrimary" )},
            { (CabinDrawNumber.Draw9S9F9F,              CabinSynthesisModel.Primary), GetSideSketchDrawImage("SFFPrimary" )},
            { (CabinDrawNumber.Draw94,                  CabinSynthesisModel.Primary), GetSideSketchDrawImage("4" )},
            { (CabinDrawNumber.Draw949F,                CabinSynthesisModel.Primary), GetSideSketchDrawImage("4FPrimary" )},
            { (CabinDrawNumber.Draw949F9F,              CabinSynthesisModel.Primary), GetSideSketchDrawImage("4FFPrimary" )},
            { (CabinDrawNumber.Draw9A,                  CabinSynthesisModel.Primary), GetSideSketchDrawImage("APrimary" )},
            { (CabinDrawNumber.Draw9A9F,                CabinSynthesisModel.Primary), GetSideSketchDrawImage("AFPrimary" )},
            { (CabinDrawNumber.Draw9C,                  CabinSynthesisModel.Primary), GetSideSketchDrawImage("CPrimary" )},
            { (CabinDrawNumber.Draw9C9F,                CabinSynthesisModel.Primary), GetSideSketchDrawImage("CFPrimary" )},
            { (CabinDrawNumber.Draw9B,                  CabinSynthesisModel.Primary), GetSideSketchDrawImage("BPrimary" )},
            { (CabinDrawNumber.Draw9B9F,                CabinSynthesisModel.Primary), GetSideSketchDrawImage("BFPrimary" )},
            { (CabinDrawNumber.Draw9B9F9F,              CabinSynthesisModel.Primary), GetSideSketchDrawImage("BFFPrimary" )},
            { (CabinDrawNumber.DrawVS,                  CabinSynthesisModel.Primary), GetSideSketchDrawImage("SPrimary" )},
            { (CabinDrawNumber.DrawVSVF,                CabinSynthesisModel.Primary), GetSideSketchDrawImage("SFPrimary" )},
            { (CabinDrawNumber.DrawV4,                  CabinSynthesisModel.Primary), GetSideSketchDrawImage("4" )},
            { (CabinDrawNumber.DrawV4VF,                CabinSynthesisModel.Primary), GetSideSketchDrawImage("4FPrimary" )},
            { (CabinDrawNumber.DrawVA,                  CabinSynthesisModel.Primary), GetSideSketchDrawImage("APrimary" )},
            { (CabinDrawNumber.DrawWS,                  CabinSynthesisModel.Primary), GetSideSketchDrawImage("WSPrimary" )},
            { (CabinDrawNumber.DrawNP44,                CabinSynthesisModel.Primary), GetSideSketchDrawImage("44Primary" )},
            { (CabinDrawNumber.Draw2CornerNP46,         CabinSynthesisModel.Primary), GetSideSketchDrawImage("46Primary" )},
            { (CabinDrawNumber.Draw2StraightNP48,       CabinSynthesisModel.Primary), GetSideSketchDrawImage("48Primary" )},
            { (CabinDrawNumber.DrawCornerNP6W45,        CabinSynthesisModel.Primary), GetSideSketchDrawImage("45Primary" )},
            { (CabinDrawNumber.DrawStraightNP6W47,      CabinSynthesisModel.Primary), GetSideSketchDrawImage("47Primary" )},
            { (CabinDrawNumber.DrawNB31,                CabinSynthesisModel.Primary), GetSideSketchDrawImage("31Primary" )},
            { (CabinDrawNumber.DrawCornerNB6W32,        CabinSynthesisModel.Primary), GetSideSketchDrawImage("32Primary" )},
            { (CabinDrawNumber.Draw2CornerNB33,         CabinSynthesisModel.Primary), GetSideSketchDrawImage("33Primary" )},
            { (CabinDrawNumber.DrawStraightNB6W38,      CabinSynthesisModel.Primary), GetSideSketchDrawImage("38Primary" )},
            { (CabinDrawNumber.Draw2StraightNB41,       CabinSynthesisModel.Primary), GetSideSketchDrawImage("41Primary" )},
            { (CabinDrawNumber.DrawDB51,                CabinSynthesisModel.Primary), GetSideSketchDrawImage("51Primary" )},
            { (CabinDrawNumber.DrawCornerDB8W52,        CabinSynthesisModel.Primary), GetSideSketchDrawImage("52Primary" )},
            { (CabinDrawNumber.Draw2CornerDB53,         CabinSynthesisModel.Primary), GetSideSketchDrawImage("53Primary" )},
            { (CabinDrawNumber.DrawStraightDB8W59,      CabinSynthesisModel.Primary), GetSideSketchDrawImage("59Primary" )},
            { (CabinDrawNumber.Draw2StraightDB61,       CabinSynthesisModel.Primary), GetSideSketchDrawImage("61Primary" )},
            { (CabinDrawNumber.DrawHB34,                CabinSynthesisModel.Primary), GetSideSketchDrawImage("34Primary" )},
            { (CabinDrawNumber.DrawCornerHB8W35,        CabinSynthesisModel.Primary), GetSideSketchDrawImage("35Primary" )},
            { (CabinDrawNumber.Draw2CornerHB37,         CabinSynthesisModel.Primary), GetSideSketchDrawImage("37Primary" )},
            { (CabinDrawNumber.DrawStraightHB8W40,      CabinSynthesisModel.Primary), GetSideSketchDrawImage("40Primary" )},
            { (CabinDrawNumber.Draw2StraightHB43,       CabinSynthesisModel.Primary), GetSideSketchDrawImage("43Primary" )},
            { (CabinDrawNumber.Draw8W,                  CabinSynthesisModel.Primary), GetSideSketchDrawImage("WPrimary" )},
            { (CabinDrawNumber.DrawE,                   CabinSynthesisModel.Primary), GetSideSketchDrawImage("EPrimary" )},
            { (CabinDrawNumber.Draw8WFlipper81,         CabinSynthesisModel.Primary), GetSideSketchDrawImage("81Primary" )},
            { (CabinDrawNumber.Draw2Corner8W82,         CabinSynthesisModel.Primary), GetSideSketchDrawImage("82Primary" )},
            { (CabinDrawNumber.Draw1Corner8W84,         CabinSynthesisModel.Primary), GetSideSketchDrawImage("84Primary" )},
            { (CabinDrawNumber.Draw2Straight8W85,       CabinSynthesisModel.Primary), GetSideSketchDrawImage("85Primary" )},
            { (CabinDrawNumber.Draw2CornerStraight8W88, CabinSynthesisModel.Primary), GetSideSketchDrawImage("88Primary" )},
            { (CabinDrawNumber.Draw8W40,                CabinSynthesisModel.Primary), GetSideSketchDrawImage("8W40Primary" )},
            { (CabinDrawNumber.DrawNV,                  CabinSynthesisModel.Primary), GetSideSketchDrawImage("NVPrimary" )},
            { (CabinDrawNumber.DrawNV2,                 CabinSynthesisModel.Primary), GetSideSketchDrawImage("NV2Primary" )},
            { (CabinDrawNumber.DrawMV2,                 CabinSynthesisModel.Primary), GetSideSketchDrawImage("MV2Primary" )},
            { (CabinDrawNumber.Draw9F,                  CabinSynthesisModel.Primary), GetSideSketchDrawImage("FPrimary" )},
            { (CabinDrawNumber.DrawVF,                  CabinSynthesisModel.Primary), GetSideSketchDrawImage("FPrimary" )},
            { (CabinDrawNumber.DrawQP44,                CabinSynthesisModel.Primary), GetSideSketchDrawImage("44Primary" )},
            { (CabinDrawNumber.Draw2CornerQP46,         CabinSynthesisModel.Primary), GetSideSketchDrawImage("46Primary" )},
            { (CabinDrawNumber.Draw2StraightQP48,       CabinSynthesisModel.Primary), GetSideSketchDrawImage("48Primary" )},
            { (CabinDrawNumber.DrawCornerQP6W45,        CabinSynthesisModel.Primary), GetSideSketchDrawImage("45Primary" )},
            { (CabinDrawNumber.DrawStraightQP6W47,      CabinSynthesisModel.Primary), GetSideSketchDrawImage("47Primary" )},
            { (CabinDrawNumber.DrawQB31,                CabinSynthesisModel.Primary), GetSideSketchDrawImage("31Primary" )},
            { (CabinDrawNumber.DrawCornerQB6W32,        CabinSynthesisModel.Primary), GetSideSketchDrawImage("32Primary" )},
            { (CabinDrawNumber.Draw2CornerQB33,         CabinSynthesisModel.Primary), GetSideSketchDrawImage("33Primary" )},
            { (CabinDrawNumber.DrawStraightQB6W38,      CabinSynthesisModel.Primary), GetSideSketchDrawImage("38Primary" )},
            { (CabinDrawNumber.Draw2StraightQB41,       CabinSynthesisModel.Primary), GetSideSketchDrawImage("41Primary" )},

            { (CabinDrawNumber.None,                    CabinSynthesisModel.Secondary), ""},
            { (CabinDrawNumber.Draw9S,                  CabinSynthesisModel.Secondary), ""},
            { (CabinDrawNumber.Draw9S9F,                CabinSynthesisModel.Secondary), GetSideSketchDrawImage("SFSecondary" )},
            { (CabinDrawNumber.Draw9S9F9F,              CabinSynthesisModel.Secondary), GetSideSketchDrawImage("SFFSecondary" )},
            { (CabinDrawNumber.Draw94,                  CabinSynthesisModel.Secondary), ""},
            { (CabinDrawNumber.Draw949F,                CabinSynthesisModel.Secondary), GetSideSketchDrawImage("4FSecondary" )},
            { (CabinDrawNumber.Draw949F9F,              CabinSynthesisModel.Secondary), GetSideSketchDrawImage("4FFSecondary" )},
            { (CabinDrawNumber.Draw9A,                  CabinSynthesisModel.Secondary), GetSideSketchDrawImage("ASecondary" )},
            { (CabinDrawNumber.Draw9A9F,                CabinSynthesisModel.Secondary), GetSideSketchDrawImage("AFSecondary" )},
            { (CabinDrawNumber.Draw9C,                  CabinSynthesisModel.Secondary), GetSideSketchDrawImage("CSecondary" )},
            { (CabinDrawNumber.Draw9C9F,                CabinSynthesisModel.Secondary), GetSideSketchDrawImage("CFSecondary" )},
            { (CabinDrawNumber.Draw9B,                  CabinSynthesisModel.Secondary), ""},
            { (CabinDrawNumber.Draw9B9F,                CabinSynthesisModel.Secondary), GetSideSketchDrawImage("BFSecondary" )},
            { (CabinDrawNumber.Draw9B9F9F,              CabinSynthesisModel.Secondary), GetSideSketchDrawImage("BFFSecondary" )},
            { (CabinDrawNumber.DrawVS,                  CabinSynthesisModel.Secondary), ""},
            { (CabinDrawNumber.DrawVSVF,                CabinSynthesisModel.Secondary), GetSideSketchDrawImage("SFSecondary" )},
            { (CabinDrawNumber.DrawV4,                  CabinSynthesisModel.Secondary), ""},
            { (CabinDrawNumber.DrawV4VF,                CabinSynthesisModel.Secondary), GetSideSketchDrawImage("4FSecondary" )},
            { (CabinDrawNumber.DrawVA,                  CabinSynthesisModel.Secondary), GetSideSketchDrawImage("ASecondary" )},
            { (CabinDrawNumber.DrawWS,                  CabinSynthesisModel.Secondary), ""},
            { (CabinDrawNumber.DrawNP44,                CabinSynthesisModel.Secondary), ""},
            { (CabinDrawNumber.Draw2CornerNP46,         CabinSynthesisModel.Secondary), GetSideSketchDrawImage("46Secondary" )},
            { (CabinDrawNumber.Draw2StraightNP48,       CabinSynthesisModel.Secondary), GetSideSketchDrawImage("48Secondary" )},
            { (CabinDrawNumber.DrawCornerNP6W45,        CabinSynthesisModel.Secondary), GetSideSketchDrawImage("45Seconary" )},
            { (CabinDrawNumber.DrawStraightNP6W47,      CabinSynthesisModel.Secondary), GetSideSketchDrawImage("47Secondary" )},
            { (CabinDrawNumber.DrawNB31,                CabinSynthesisModel.Secondary), ""},
            { (CabinDrawNumber.DrawCornerNB6W32,        CabinSynthesisModel.Secondary), GetSideSketchDrawImage("32Secondary" )},
            { (CabinDrawNumber.Draw2CornerNB33,         CabinSynthesisModel.Secondary), GetSideSketchDrawImage("33Secondary" )},
            { (CabinDrawNumber.DrawStraightNB6W38,      CabinSynthesisModel.Secondary), GetSideSketchDrawImage("38Secondary" )},
            { (CabinDrawNumber.Draw2StraightNB41,       CabinSynthesisModel.Secondary), GetSideSketchDrawImage("41Secondary" )},
            { (CabinDrawNumber.DrawDB51,                CabinSynthesisModel.Secondary), ""},
            { (CabinDrawNumber.DrawCornerDB8W52,        CabinSynthesisModel.Secondary), GetSideSketchDrawImage("52Secondary" )},
            { (CabinDrawNumber.Draw2CornerDB53,         CabinSynthesisModel.Secondary), GetSideSketchDrawImage("53Secondary" )},
            { (CabinDrawNumber.DrawStraightDB8W59,      CabinSynthesisModel.Secondary), GetSideSketchDrawImage("59Secondary" )},
            { (CabinDrawNumber.Draw2StraightDB61,       CabinSynthesisModel.Secondary), GetSideSketchDrawImage("61Secondary" )},
            { (CabinDrawNumber.DrawHB34,                CabinSynthesisModel.Secondary), ""},
            { (CabinDrawNumber.DrawCornerHB8W35,        CabinSynthesisModel.Secondary), GetSideSketchDrawImage("35Secondary" )},
            { (CabinDrawNumber.Draw2CornerHB37,         CabinSynthesisModel.Secondary), GetSideSketchDrawImage("37Secondary" )},
            { (CabinDrawNumber.DrawStraightHB8W40,      CabinSynthesisModel.Secondary), GetSideSketchDrawImage("40Secondary" )},
            { (CabinDrawNumber.Draw2StraightHB43,       CabinSynthesisModel.Secondary), GetSideSketchDrawImage("43Secondary" )},
            { (CabinDrawNumber.Draw8W,                  CabinSynthesisModel.Secondary), ""},
            { (CabinDrawNumber.DrawE,                   CabinSynthesisModel.Secondary), ""},
            { (CabinDrawNumber.Draw8WFlipper81,         CabinSynthesisModel.Secondary), GetSideSketchDrawImage("81Secondary" )},
            { (CabinDrawNumber.Draw2Corner8W82,         CabinSynthesisModel.Secondary), GetSideSketchDrawImage("82Secondary" )},
            { (CabinDrawNumber.Draw1Corner8W84,         CabinSynthesisModel.Secondary), GetSideSketchDrawImage("84Secondary" )},
            { (CabinDrawNumber.Draw2Straight8W85,       CabinSynthesisModel.Secondary), GetSideSketchDrawImage("85Secondary" )},
            { (CabinDrawNumber.Draw2CornerStraight8W88, CabinSynthesisModel.Secondary), GetSideSketchDrawImage("88Secondary" )},
            { (CabinDrawNumber.Draw8W40,                CabinSynthesisModel.Secondary), "" },
            { (CabinDrawNumber.DrawNV,                  CabinSynthesisModel.Secondary), "" },
            { (CabinDrawNumber.DrawNV2,                 CabinSynthesisModel.Secondary), "" },
            { (CabinDrawNumber.DrawMV2,                 CabinSynthesisModel.Secondary), "" },
            { (CabinDrawNumber.Draw9F,                  CabinSynthesisModel.Secondary), "" },
            { (CabinDrawNumber.DrawVF,                  CabinSynthesisModel.Secondary), "" },
            { (CabinDrawNumber.DrawQP44,                CabinSynthesisModel.Secondary), ""},
            { (CabinDrawNumber.Draw2CornerQP46,         CabinSynthesisModel.Secondary), GetSideSketchDrawImage("46Secondary" )},
            { (CabinDrawNumber.Draw2StraightQP48,       CabinSynthesisModel.Secondary), GetSideSketchDrawImage("48Secondary" )},
            { (CabinDrawNumber.DrawCornerQP6W45,        CabinSynthesisModel.Secondary), GetSideSketchDrawImage("45Seconary" )},
            { (CabinDrawNumber.DrawStraightQP6W47,      CabinSynthesisModel.Secondary), GetSideSketchDrawImage("47Secondary" )},
            { (CabinDrawNumber.DrawQB31,                CabinSynthesisModel.Secondary), ""},
            { (CabinDrawNumber.DrawCornerQB6W32,        CabinSynthesisModel.Secondary), GetSideSketchDrawImage("32Secondary" )},
            { (CabinDrawNumber.Draw2CornerQB33,         CabinSynthesisModel.Secondary), GetSideSketchDrawImage("33Secondary" )},
            { (CabinDrawNumber.DrawStraightQB6W38,      CabinSynthesisModel.Secondary), GetSideSketchDrawImage("38Secondary" )},
            { (CabinDrawNumber.Draw2StraightQB41,       CabinSynthesisModel.Secondary), GetSideSketchDrawImage("41Secondary" )},

            { (CabinDrawNumber.None,                    CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw9S,                  CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw9S9F,                CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw9S9F9F,              CabinSynthesisModel.Tertiary), GetSideSketchDrawImage("SFFTertiary") },
            { (CabinDrawNumber.Draw94,                  CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw949F,                CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw949F9F,              CabinSynthesisModel.Tertiary), GetSideSketchDrawImage("4FFTertiary") },
            { (CabinDrawNumber.Draw9A,                  CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw9A9F,                CabinSynthesisModel.Tertiary), GetSideSketchDrawImage("AFTertiary") },
            { (CabinDrawNumber.Draw9C,                  CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw9C9F,                CabinSynthesisModel.Tertiary), GetSideSketchDrawImage("CFTertiary") },
            { (CabinDrawNumber.Draw9B,                  CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw9B9F,                CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw9B9F9F,              CabinSynthesisModel.Tertiary), GetSideSketchDrawImage("BFFTertiary") },
            { (CabinDrawNumber.DrawVS,                  CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.DrawVSVF,                CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.DrawV4,                  CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.DrawV4VF,                CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.DrawVA,                  CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.DrawWS,                  CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.DrawNP44,                CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw2CornerNP46,         CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw2StraightNP48,       CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.DrawCornerNP6W45,        CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.DrawStraightNP6W47,      CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.DrawNB31,                CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.DrawCornerNB6W32,        CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw2CornerNB33,         CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.DrawStraightNB6W38,      CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw2StraightNB41,       CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.DrawDB51,                CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.DrawCornerDB8W52,        CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw2CornerDB53,         CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.DrawStraightDB8W59,      CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw2StraightDB61,       CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.DrawHB34,                CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.DrawCornerHB8W35,        CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw2CornerHB37,         CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.DrawStraightHB8W40,      CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw2StraightHB43,       CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw8W,                  CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.DrawE,                   CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw8WFlipper81,         CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw2Corner8W82,         CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw1Corner8W84,         CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw2Straight8W85,       CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw2CornerStraight8W88, CabinSynthesisModel.Tertiary), GetSideSketchDrawImage("88Tertiary") },
            { (CabinDrawNumber.Draw8W40,                CabinSynthesisModel.Tertiary), "" },
            { (CabinDrawNumber.DrawNV,                  CabinSynthesisModel.Tertiary), "" },
            { (CabinDrawNumber.DrawNV2,                 CabinSynthesisModel.Tertiary), "" },
            { (CabinDrawNumber.DrawMV2,                 CabinSynthesisModel.Tertiary), "" },
            { (CabinDrawNumber.Draw9F,                  CabinSynthesisModel.Tertiary), "" },
            { (CabinDrawNumber.DrawVF,                  CabinSynthesisModel.Tertiary), "" },
            { (CabinDrawNumber.DrawQP44,                CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw2CornerQP46,         CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw2StraightQP48,       CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.DrawCornerQP6W45,        CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.DrawStraightQP6W47,      CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.DrawQB31,                CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.DrawCornerQB6W32,        CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw2CornerQB33,         CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.DrawStraightQB6W38,      CabinSynthesisModel.Tertiary), ""},
            { (CabinDrawNumber.Draw2StraightQB41,       CabinSynthesisModel.Tertiary), ""},
    };
}
